- build.gradle
- src/main/java/com/untitled/cherrymap/config/OpenApiConfig.java
- src/main/java/com/untitled/cherrymap/controller/AlertMessageController.java
- src/main/java/com/untitled/cherrymap/domain/AlertMessage.java
- src/main/java/com/untitled/cherrymap/domain/Member.java
- src/main/java/com/untitled/cherrymap/domain/Route.java
- src/main/java/com/untitled/cherrymap/domain/RouteRequest.java
- src/main/java/com/untitled/cherrymap/domain/Station.java
- src/main/resources/application.properties
> Swagger ui 이용한 API 문서화 #14
> Api 문서화를 위해 라이브러리 추가 및 swagger 관련 환경 설정
> 컨트롤러(아직은 AlertMessageController에만 해논 상태) 및 5개 domain(AlertMessage,Member,Route,RouteRequest,Station)에 swagger 관련 annotation 추가
> 남은 controller에 annotation 추가 부탁드립니다!!
> Chore: Swagger ui 이용한 API 문서화

- src/main/java/com/untitled/cherrymap/repository/AlertMessageRepository.java
- src/main/java/com/untitled/cherrymap/repository/MemberRepository.java
- src/main/resources/application-dev.properties
> 병합 충돌 해결 중 누락된 파일 추가
- AlertMessageRepository.java
- MemberRepository.java
- application-dev.properties
> Fix: 병합 충돌 해결 중 누락된 파일 추가

- src/main/resources/application-prod.properties
> `application-prod.properties` DB 연결 주소(spring.datasource.url)수정
- `postgres-container:5432 `->` localhost:5432`
> Fix: prod 설정 DB 연결 주소 수정

- src/main/java/com/untitled/cherrymap/repository/AlertMessageRepository.java
Reverts GDSC-Hongik/cherrymap-untitled-server#25
> Revert "refactor: 테이블 생성하지 않기 위해 AlertMesaageRepository 삭제"

- src/main/java/com/untitled/cherrymap/controller/AlertMessageController.java
- src/main/java/com/untitled/cherrymap/domain/AlertMessage.java
- src/main/java/com/untitled/cherrymap/domain/RouteRequest.java
- src/main/java/com/untitled/cherrymap/repository/AlertMessageRepository.java
> alertmessage, routerequest 관련 swagger ui 대중교통 example 수정
> AlertMessageController 엔드포인트에 '/api'추가
> Refactor: swagger ui example 수정 및 AlertMessageController 엔드포인트 수정

- build.gradle
> swagger ui 오류 해결을 위해 가장 최신 버전으로 변경
> refactor: swagger ui 가장 최신 버전으로 변경

- src/main/java/com/untitled/cherrymap/config/SecurityConfig.java
> CORS 이슈 해결
- `SecurityConfig.java` 수정
- `corsConfigurationSource` 설정 추가
- `SecurityFilterChain`에 cors 설정 추가
> Fix: SecurityConfig CORS 이슈 해결

- src/main/java/com/untitled/cherrymap/config/SecurityConfig.java
> #38
> corsconfig에 localhost:5173 추가
> Chore: corsconfig에 localhost:5173 추가

- src/main/java/com/untitled/cherrymap/config/SecurityConfig.java
- src/main/java/com/untitled/cherrymap/controller/MemberController.java
- src/main/java/com/untitled/cherrymap/exception/GlobalExceptionHandler.java
- src/main/java/com/untitled/cherrymap/service/MemberService.java
> #40 #41
> 비상 연락처 API 구현 & 유효성 검증 오류 처리 -> 배포 브랜츠(main)에 반영
> 없음.
> Feat/Refact: 비상 연락처 API 추가, 유효성 검증 오류 처리 메서드 추가

- src/main/java/com/untitled/cherrymap/dto/PhoneNumberRequest.java
> #40 비상 연락처 API 구현
> 비상 연락처 DTO `PhoneNumberRequest`를 추가
> feat: 비상 연락처 DTO PhoneNumberRequest 추가

- .github/workflows/cherrymap.yml
- Dockerfile
- src/main/java/com/untitled/cherrymap/domain/member/domain/Member.java
- src/main/java/com/untitled/cherrymap/domain/route/domain/Route.java
- src/main/java/com/untitled/cherrymap/security/jwt/refresh/Refresh.java
- src/main/resources/application-prod.properties
> #50 
> - Dockerfile + Git Actions workflow를 포함하는 `cherrymap.yml` 파일을 통한 CI/CD 배포 환경 구축.
> - `application-prod.properties` 를 새로운 서버 환경에 맞게 수정.
새로운 서버 배포를 위해 `main`에 직접 push함으로써 발생한 `dev`와 `main` 사이 파일의 간극을 줄이는 목적의 PR이며,
`main`에 추가했었던 파일을 `astrokan` 브랜치로 옮겨온 후 `dev`에 반영하는 작업입니다.
> Chore&Refactor: CI/CD 관련 파일 업로드, DB ERD 기반의 전체 엔티티 수정

- src/main/java/com/untitled/cherrymap/domain/route/api/RouteController.java
- src/main/java/com/untitled/cherrymap/domain/route/application/RouteService.java
- src/main/java/com/untitled/cherrymap/domain/route/dao/RouteRepository.java
- src/main/java/com/untitled/cherrymap/domain/route/dto/RouteCreateRequest.java
- src/main/java/com/untitled/cherrymap/domain/route/dto/RouteRequest.java
> chore: 에러 코드 주석 처리

- .github/workflows/cherrymap.yml
- src/main/resources/application-prod.properties
> jwt.secret을 git actions에 저장하여 넘김.
> chore: jwt secret 오류 수정

- src/main/java/com/untitled/cherrymap/common/config/SecurityConfig.java
> chore: security 허용 경로 수정

- src/main/java/com/untitled/cherrymap/domain/member/domain/Member.java
- src/main/java/com/untitled/cherrymap/domain/route/application/RouteService.java
- src/main/java/com/untitled/cherrymap/domain/route/dao/RouteRepository.java
- src/main/java/com/untitled/cherrymap/domain/route/domain/Route.java
- src/main/java/com/untitled/cherrymap/domain/route/dto/RouteCreateRequest.java
- src/main/java/com/untitled/cherrymap/security/JoinService.java
- src/main/java/com/untitled/cherrymap/security/dto/CustomUserDetailsDTO.java
- src/main/java/com/untitled/cherrymap/security/jwt/refresh/ReissueService.java
> 
> enum 타입 변경 작업[member의 userRole, route의 mode]
> fix: enum 타입 변경 작업

- build.gradle
- src/main/resources/application-prod.properties
Reverts gdg-hongik-univ/cherrymap-untitled-server#60
> Revert "chore: Dev -> Main"

- src/main/java/com/untitled/cherrymap/domain/member/domain/Member.java
- src/main/java/com/untitled/cherrymap/domain/member/domain/UserRole.java
- src/main/java/com/untitled/cherrymap/domain/route/domain/Route.java
- src/main/java/com/untitled/cherrymap/domain/route/domain/RouteMode.java
> fix: enum 필드 변경 작업[member, route]
>
> fix: enum 필드 변경 작업

- src/main/java/com/untitled/cherrymap/common/config/SecurityConfig.java
- src/main/java/com/untitled/cherrymap/security/DevTokenController.java
> feat: 임시 토큰 발급 기능 구현

- src/main/java/com/untitled/cherrymap/common/config/SecurityConfig.java
- src/main/java/com/untitled/cherrymap/security/DevTokenController.java
> main으로 merge

- src/main/java/com/untitled/cherrymap/common/config/OpenApiConfig.java
- src/main/java/com/untitled/cherrymap/common/config/SecurityConfig.java
> #50 #84 
merge into main prod.branch
> fix: Add CORS configuration for cherrymap.click domain

- src/main/java/com/untitled/cherrymap/domain/route/application/RouteService.java
- src/main/java/com/untitled/cherrymap/domain/route/dto/RouteResponse.java
> refactor: RouteResponse 필드 추가

- src/main/java/com/untitled/cherrymap/common/config/SecurityConfig.java
- src/main/java/com/untitled/cherrymap/domain/emotion/api/EmotionController.java
- src/main/java/com/untitled/cherrymap/domain/emotion/application/EmotionService.java
- src/main/java/com/untitled/cherrymap/domain/emotion/dao/EmotionRepository.java
- src/main/java/com/untitled/cherrymap/domain/emotion/domain/Emotion.java
- src/main/java/com/untitled/cherrymap/domain/emotion/domain/EmotionType.java
- src/main/java/com/untitled/cherrymap/domain/emotion/dto/EmotionRequest.java
- src/main/java/com/untitled/cherrymap/domain/emotion/dto/EmotionResponse.java
- src/main/java/com/untitled/cherrymap/domain/emotion/exception/EmotionErrorCode.java
- src/main/java/com/untitled/cherrymap/domain/emotion/exception/EmotionNotFoundException.java
- src/main/java/com/untitled/cherrymap/domain/route/application/RouteService.java
- src/main/java/com/untitled/cherrymap/domain/route/domain/Route.java
- src/main/java/com/untitled/cherrymap/domain/route/dto/RouteResponse.java
- src/main/java/com/untitled/cherrymap/domain/route/exception/RouteNotFoundException.java
> feat: 감정 기록 기능 추가

- src/main/java/com/untitled/cherrymap/common/config/SecurityConfig.java
> refactor: 헤더에 access, set-cookie 추가

- src/main/java/com/untitled/cherrymap/domain/member/application/MemberService.java
member가 JPA가 관리하는 영속 엔티티가 아닐 수 있는 상태
-> member.setPhoneNumber() 해도 JPA는 이 변경을 감지하지 않기 때문에 DB에 반영되지 않음.
member를 영속 엔티티로 가져오는 메서드(`getPersistentMember`) 만들어서 member 쓸 때마다 사용 
>
> refactor: member를 영속 객체로 가져오도록 수정

- src/main/java/com/untitled/cherrymap/domain/llm/api/LlmController.java
- src/main/java/com/untitled/cherrymap/domain/llm/application/LlmService.java
> refactor: LLM 관련 로그 제거
